baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
canonifyurls = true
pygmentsCodefences = true
googleAnalytics = 'UA-77722104-1'
Authors = 'Surya Efendi'

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[module]
  [[module.mounts]]
      source = "static/css"
      target = "assets/css"

  [[module.mounts]]
      source = "static/css/color"
      target = "assets/css/color"

  [[module.mounts]]
      source = "static/img"
      target = "assets/img"
  
  [[module.mounts]]
      source = "static/js"
      target = "assets/js"
  
  
[Social]
  facebook = 'abcdeg.maas'

[permalinks]
  post = '/:slug/'

[params]
  subtitle = "Gak tau apa"
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "post"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

  [params.twitter]
    # set Twitter handles for Twitter cards
    # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
    # do not include @
    creator = "uyhaa_zxcf"
    site = "uyhaa_zxcf"

[languages]
  [languages.en]
    languageName = "English"
    title = "lightning-x"
    subtitle = "simple blog"
    owner = "Surya Efendi"
    keywords = ""
    copyright = ""
    menuMore = "Tampil Selengkapnya"
    readMore = "Baca Selengkapnya"
    readOtherPosts = "Baca Artikel lainnya"
    newerPosts = "Artikel baru"
    olderPosts = "Artikel lama"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Kembali ke halaman utama"

    [languages.en.params.logo]
      logoText = "lightning-x"
      logoHomeLink = "/"

    # [languages.en.menu]
    #   [[languages.en.menu.main]]
    #     identifier = "about"
    #     name = "About"
    #     url = "/about"
    #   [[languages.en.menu.main]]
    #     identifier = "showcase"
    #     name = "Showcase"
    #     url = "/showcase"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe= true
  
  [markup.highlight]
    
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4